version: "3.8"
services:
  checkboxes:
    image: oven/bun:latest
    container_name: checkboxes
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 6968:6969
    working_dir: /app
    command: bun .
    volumes:
      - /home/lyall/Servers/Checkboxes:/app
