version: "3.8"
services:
  download_test:
    image: node
    container_name: download_test
    restart: unless-stopped
    network_mode: host
    working_dir: /app
    command: node ./server.js
    volumes:
      - /home/lyall/Servers/Download-Test:/app