version: "3.8"
services:
  museum:
    image: ghcr.io/ente-io/server
    container_name: ente_museum
    ports:
      - 5429:8080 # API
      - 5430:2112 # Prometheus metrics
    depends_on:
      - postgres
    environment:
      ENTE_CREDENTIALS_FILE: /credentials.yaml
    volumes:
      - ../volumes/ente/museum/museum.yaml:/museum.yaml:ro
      - ../volumes/ente/scripts/compose/credentials.yaml:/credentials.yaml:ro
      - ../volumes/ente/data:/data:ro
    networks:
      - internal

  socat:
    image: alpine/socat
    network_mode: service:museum
    container_name: ente_socat
    depends_on:
      - museum
    command: "TCP-LISTEN:3200,fork,reuseaddr TCP:minio:3200"

  postgres:
    image: postgres:12
    container_name: ente_postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: ente_db
    volumes:
      - ../volumes/ente/postgres-data:/var/lib/postgresql/data
    networks:
      - internal

  minio:
    image: minio/minio
    container_name: ente_minio
    ports:
      - 3200:3200 # API
      - 3201:3201 # Console
    environment:
      MINIO_ROOT_USER: test
      MINIO_ROOT_PASSWORD: testtest
    command: server /data --address ":3200" --console-address ":3201"
    volumes:
      - ../volumes/ente/minio-data:/data
    networks:
      - internal

  minio_provision:
    image: minio/mc
    container_name: ente_minio_provision
    depends_on:
      - minio
    volumes:
      - ../volumes/ente/scripts/compose/minio-provision.sh:/provision.sh:ro
      - ../volumes/ente/minio-data:/data
    networks:
      - internal
    entrypoint: sh /provision.sh

networks:
  internal:
    name: ente_network