version: "3.8"
services:
  http_test:
    image: oven/bun:latest
    container_name: http_test
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 5678:5678
    working_dir: /app
    command: bun .
    volumes:
      - /home/lyall/Servers/HTTP-Test:/app