version: "3.8"
services:
  redis:
    image: redis:alpine
    container_name: mailu_redis
    restart: unless-stopped
    volumes:
      - ../volumes/mailu/redis:/data
    depends_on:
      - resolver
    # dns:
      # - 172.17.0.254
  front:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}nginx:${MAILU_VERSION:-2024.06}
    container_name: mailu_front
    # networks:
      # - default
      # - webmail
    network_mode: bridge
    restart: unless-stopped
    env_file: ../volumes/mailu/mailu.env
    # dns:
      # - 172.17.0.254
    ports:
      - 5310:80
      - 5311:443
      - 25:25
      - 465:465
      - 587:587
      - 110:110
      - 995:995
      - 143:143
      - 993:993
      - 4190:4190
    volumes:
      - ../volumes/mailu/certs:/certs
      - ../volumes/mailu/overrides/nginx:/overrides:ro
    depends_on:
      - resolver
  resolver:
    # networks:
      # - mailu_network
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}unbound:${MAILU_VERSION:-2024.06}
    container_name: mailu_resolver
    network_mode: bridge
    env_file: ../volumes/mailu/mailu.env
    restart: unless-stopped
    # networks:
        # default:
          # ipv4_address: 172.17.0.254
  admin:
    # dns:
      # - 172.17.0.254
    # networks:
      # - mailu_network
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}admin:${MAILU_VERSION:-2024.06}
    container_name: mailu_admin
    network_mode: bridge
    restart: unless-stopped
    env_file: ../volumes/mailu/mailu.env
    volumes:
      - ../volumes/mailu/data:/data
      - ../volumes/mailu/dkim:/dkim
    depends_on:
      - redis
      - resolver
  imap:
    # networks:
      # - default
    # dns:
      # - 172.17.0.254
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}dovecot:${MAILU_VERSION:-2024.06}
    container_name: mailu_imap
    network_mode: bridge
    restart: unless-stopped
    env_file: ../volumes/mailu/mailu.env
    volumes:
      - ../volumes/mailu/mail:/mail
      - ../volumes/mailu/overrides/dovecot:/overrides:ro
    depends_on:
      - front
      - resolver
  smtp:
    # networks:
      # - mailu_network
    # dns:
      # - 172.17.0.254
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}postfix:${MAILU_VERSION:-2024.06}
    container_name: mailu_smtp
    network_mode: bridge
    restart: unless-stopped
    env_file: ../volumes/mailu/mailu.env
    volumes:
      - ../volumes/mailu/mailqueue:/queue
      - ../volumes/mailu/overrides/postfix:/overrides:ro
    depends_on:
      - front
      - resolver
  oletools:
    # networks:
      # - oletools
    # dns:
      # - 172.17.0.254
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}oletools:${MAILU_VERSION:-2024.06}
    container_name: mailu_oletools
    network_mode: bridge
    restart: unless-stopped
    depends_on:
      - resolver
  antispam:
    # networks:
      # - mailu_network
    # dns:
      # - 172.17.0.254
    # networks:
      # - default
      # - oletools
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}rspamd:${MAILU_VERSION:-2024.06}
    container_name: mailu_antispam
    network_mode: bridge
    restart: unless-stopped
    env_file: ../volumes/mailu/mailu.env
    volumes:
      - ../volumes/mailu/filter:/var/lib/rspamd
      - ../volumes/mailu/overrides/rspamd:/overrides:ro
    depends_on:
      - front
      - redis
      - oletools
      - resolver
  webmail:
    # networks:
      # - mailu_network
    # dns:
      # - 172.69.0.254
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}webmail:${MAILU_VERSION:-2024.06}
    container_name: mailu_webmail
    network_mode: bridge
    # networks:
      # - webmail
    restart: unless-stopped
    env_file: ../volumes/mailu/mailu.env
    volumes:
      - ../volumes/mailu/webmail:/data
      - ../volumes/mailu/overrides/roundcube:/overrides:ro
    depends_on:
      - front

# networks:
#   default:
#     driver: bridge
#     ipam:
#       driver: default
#       config:
#         - subnet: 172.17.0.0/24
#   webmail:
#     driver: bridge
#   oletools:
#     driver: bridge
#     internal: true
