version: "3.8"
services:
  database:
    image: mariadb:10.5
    container_name: pterodactyl_database
    network_mode: bridge
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ../volumes/pterodactyl_database/database:/var/lib/mysql
    environment:
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password123
      MYSQL_DATABASE: panel
      MYSQL_USER: pterodactyl
  cache:
    image: redis:alpine
    container_name: pterodactyl_cache
    network_mode: bridge
    restart: unless-stopped
  panel:
    image: ghcr.io/pterodactyl/panel:latest
    container_name: pterodactyl_panel
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 8999:80
      - 9000:443
    links:
      - database
      - cache
    volumes:
      - ../volumes/pterodactyl_panel/var:/app/var
      - ../volumes/pterodactyl_panel/nginx:/etc/nginx/http.d
      - ../volumes/pterodactyl_panel/certs:/etc/letsencrypt
      - ../volumes/pterodactyl_panel/logs:/app/storage/logs
    environment:
      # A list of valid timezones can be found here: http://php.net/manual/en/timezones.php
      APP_TIMEZONE: Europe/London
      DB_PASSWORD: password
      APP_ENV: production
      APP_ENVIRONMENT_ONLY: "false"
      CACHE_DRIVER: redis
      SESSION_DRIVER: redis
      QUEUE_DRIVER: redis
      REDIS_HOST: cache
      DB_HOST: database
      DB_PORT: "3306"
  wings:
    image: ghcr.io/pterodactyl/wings:latest
    container_name: pterodactyl_wings
    restart: unless-stopped
    environment:
      TZ: Europe/London
    network_mode: bridge
    ports:
      - 8098:443
      - 2022:2022
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - ../volumes/pterodactyl_wings/tmp:/tmp/pterodactyl
      - ../volumes/pterodactyl_wings/certs:/etc/ssl/certs
      - ../volumes/pterodactyl_wings/etc:/etc/pterodactyl
      - ../volumes/pterodactyl_wings/logs:/var/log/pterodactyl
      - ../volumes/pterodactyl_panel/var:/var/lib/pterodactyl