version: "3.8"
services:
  ryot_db:
    image: postgres:16-alpine
    container_name: ryot_db
    restart: unless-stopped
    #network_mode: bridge
    volumes:
      - ../volumes/ryot/ryot_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
  ryot:
    image: ignisda/ryot:v7
    container_name: ryot
    restart: unless-stopped
    #network_mode: bridge
    ports:
      - 4931:8000
    environment:
      - DATABASE_URL=postgres://postgres:postgres@ryot_db:5432/postgres
