version: "3.8"
services:
  tcp_proxy:
    image: node
    container_name: tcp_proxy
    restart: unless-stopped
    network_mode: host
    working_dir: /app
    command: node .
    volumes:
      - /home/lyall/Servers/Simple-TCP-Proxy:/app
