version: "3.8"
services:
  music_assistant:
    image: ghcr.io/music-assistant/server
    container_name: music_assistant
    restart: unless-stopped
    network_mode: host
    privileged: true
    volumes:
      - ../volumes/music_assistant/data:/data
      - /media/hdd/media:/media
