services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    restart: unless-stopped
    network_mode: host
    # network_mode: bridge
    # ports:
    #   - 53:53/tcp
    #   - 53:53/udp
    #   - 3000:3000/tcp
    volumes:
      - ../Docker volumes/adguardhome/work:/opt/adguardhome/work
      - ../Docker volumes/adguardhome/conf:/opt/adguardhome/conf