services:
  code_server:
    image: linuxserver/code-server
    container_name: code_server
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 8443:8443
    volumes:
      - ../Docker volumes/code_server/config:/config