services:
  http_proxy:
    build:
      context: .
      dockerfile: Dockerfile.http_proxy
    container_name: http_proxy
    restart: unless-stopped
    network_mode: host
    volumes:
      - ../Docker volumes/http_proxy/config.json:/data/config.json
      - ../Docker volumes/http_proxy/services:/data/services
      - ../Docker volumes/http_proxy/pages:/data/pages