services:
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 4533:4533
    volumes:
      - ../Docker volumes/navidrome/data:/data
