services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 9443:9443
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../Docker volumes/portainer/data:/data
      
  portainer_agent:
    image: portainer/agent:2.19.4
    container_name: portainer_agent
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 9001:9001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
